#!/usr/bin/env ruby

require 'pry'
require 'optparse'

USAGE = "Usage: rgrep [OPTIONS] PATTERN [FILE]"

def parse_options(args)
  options = {}
  options[:a] = 0
  parser = OptionParser.new do |opts|
    opts.banner = USAGE
    opts.on("-a NLINES", "Mandatory argument") do |arg|
      options[:a] = arg.to_i
    end
  end
  parser.parse!(args)
  options 
end

options = parse_options(ARGV)

request_expr =   options.has_key?(:fname) ? Regexp.new(options[:fname]) : 
                (! ARGV.empty?) ? Regexp.new(ARGV.shift) : (puts USAGE; exit 1)

flines = if options.key?(:fname) 
  File.open(options[:fname]).map { |l| l } 
elsif ! ARGV.empty?
  File.open(ARGV.shift).map { |l| l }
else
  STDIN.read.chomp.split("\n")
end

#flines.each { |line|  puts line if line =~ request_expr }

flines.select { |it| it =~ request_expr }.each do |line|
  line_index = flines.find_index(line)
  puts flines[line_index - options[:a], 2 * options[:a] + 1]
end
